# Generated by Django 4.1.13 on 2025-11-18 15:36

import apps.face_recognition.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('enrollment_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('insightface_embedding', models.JSONField(blank=True, null=True)),
                ('deepface_embedding', models.JSONField(blank=True, null=True)),
                ('dlib_embedding', models.JSONField(blank=True, null=True)),
                ('quality_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Data',
                'verbose_name_plural': 'Face Data',
                'db_table': 'face_data',
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_confidence_threshold', models.FloatField(default=0.6, help_text='Minimum confidence for recognition')),
                ('quality_threshold', models.FloatField(default=0.5, help_text='Minimum quality for enrollment')),
                ('insightface_weight', models.FloatField(default=0.4)),
                ('deepface_weight', models.FloatField(default=0.4)),
                ('dlib_weight', models.FloatField(default=0.2)),
                ('enable_liveness_detection', models.BooleanField(default=True)),
                ('enable_anti_spoofing', models.BooleanField(default=True)),
                ('log_all_attempts', models.BooleanField(default=True)),
                ('max_recognition_time', models.IntegerField(default=5, help_text='Seconds')),
                ('batch_processing', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Face Recognition Settings',
                'verbose_name_plural': 'Face Recognition Settings',
                'db_table': 'face_recognition_settings',
            },
        ),
        migrations.CreateModel(
            name='RecognitionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recognition_logs/')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('no_face', 'No Face Detected'), ('low_confidence', 'Low Confidence'), ('multiple_faces', 'Multiple Faces')], max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('insightface_result', models.JSONField(blank=True, null=True)),
                ('deepface_result', models.JSONField(blank=True, null=True)),
                ('dlib_result', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recognized_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recognition Log',
                'verbose_name_plural': 'Recognition Logs',
                'db_table': 'recognition_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('angle', models.CharField(choices=[('center', 'Center'), ('up', 'Up'), ('down', 'Down'), ('left', 'Left'), ('right', 'Right'), ('up_left', 'Up Left'), ('up_right', 'Up Right'), ('down_left', 'Down Left'), ('down_right', 'Down Right')], max_length=20)),
                ('image', models.ImageField(upload_to=apps.face_recognition.models.face_image_upload_path)),
                ('brightness', models.FloatField(default=0.0)),
                ('sharpness', models.FloatField(default=0.0)),
                ('face_detected', models.BooleanField(default=False)),
                ('detection_confidence', models.FloatField(default=0.0)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('face_data', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='face_recognition.facedata')),
            ],
            options={
                'verbose_name': 'Face Image',
                'verbose_name_plural': 'Face Images',
                'db_table': 'face_images',
            },
        ),
        migrations.AddIndex(
            model_name='recognitionlog',
            index=models.Index(fields=['-timestamp'], name='recognition_timesta_319d63_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionlog',
            index=models.Index(fields=['status'], name='recognition_status_e05703_idx'),
        ),
        migrations.AddIndex(
            model_name='faceimage',
            index=models.Index(fields=['angle'], name='face_images_angle_aaaec8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='faceimage',
            unique_together={('face_data', 'angle')},
        ),
        migrations.AddIndex(
            model_name='facedata',
            index=models.Index(fields=['is_complete'], name='face_data_is_comp_36a30f_idx'),
        ),
    ]
