# Generated by Django 4.1.13 on 2025-11-18 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='faculty',
            field=models.ForeignKey(db_constraint=False, limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='additional_faculty',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'faculty'}, related_name='additional_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='enrolled_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='primary_faculty',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Leave blank for all departments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='academic.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'hod'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['day_of_week'], name='timetable_day_of__f3d59b_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['is_active'], name='timetable_is_acti_16b1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['semester'], name='subjects_semeste_a88d04_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='subjects_code_3f80fa_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active'], name='subjects_is_acti_960049_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['start_date', 'end_date'], name='holidays_start_d_c44e9b_idx'),
        ),
    ]
