# Generated by Django 4.1.13 on 2025-11-18 15:36

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='absent', max_length=20)),
                ('marking_method', models.CharField(choices=[('face', 'Face Recognition'), ('manual', 'Manual'), ('qr', 'QR Code'), ('auto', 'Automatic')], default='manual', max_length=20)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('recognition_confidence', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location_verified', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('student', 'Student Report'), ('subject', 'Subject Report'), ('department', 'Department Report'), ('session', 'Session Report')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='attendance_reports/')),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('records_count', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0.0, help_text='Processing time in seconds')),
            ],
            options={
                'verbose_name': 'Attendance Report',
                'verbose_name_plural': 'Attendance Reports',
                'db_table': 'attendance_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_sessions', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('excused_count', models.IntegerField(default=0)),
                ('attendance_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_streak', models.IntegerField(default=0, help_text='Current consecutive attendance streak')),
                ('longest_streak', models.IntegerField(default=0, help_text='Longest consecutive attendance streak')),
                ('is_below_threshold', models.BooleanField(default=False, help_text='Below minimum attendance requirement')),
                ('warning_sent', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Statistics',
                'verbose_name_plural': 'Attendance Statistics',
                'db_table': 'attendance_statistics',
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Laboratory'), ('tutorial', 'Tutorial'), ('seminar', 'Seminar')], default='lecture', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('attendance_window_minutes', models.IntegerField(default=15, help_text='Minutes after start time to mark attendance')),
                ('allow_late_marking', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class Session',
                'verbose_name_plural': 'Class Sessions',
                'db_table': 'class_sessions',
                'ordering': ['-scheduled_date', '-start_time'],
            },
        ),
    ]
