# Generated by Django 4.1.13 on 2025-11-18 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('face_recognition', '0001_initial'),
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='faculty',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='taught_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsession',
            name='subject',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='attendancestatistics',
            name='student',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancestatistics',
            name='subject',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_stats', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='generated_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='recognition_log',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='face_recognition.recognitionlog'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.classsession'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['scheduled_date', 'start_time'], name='class_sessi_schedul_4c2acd_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['status'], name='class_sessi_status_6eaa64_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancestatistics',
            index=models.Index(fields=['attendance_percentage'], name='attendance__attenda_b41f54_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancestatistics',
            index=models.Index(fields=['is_below_threshold'], name='attendance__is_belo_1057cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancestatistics',
            unique_together={('student', 'subject')},
        ),
        migrations.AddIndex(
            model_name='attendancereport',
            index=models.Index(fields=['-generated_at'], name='attendance__generat_188917_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancereport',
            index=models.Index(fields=['report_type'], name='attendance__report__0dc53d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance_status_a068a7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['marked_at'], name='attendance_marked__ce655c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('session', 'student')},
        ),
    ]
